# Introduction

## About The Photographer's Guide to Los Santos
The Photographer's Guide to Los Santos sits between a touristic guide and a photography manual, and between an exhibition catalogue and a peak behind the scenes of artwork creation.

The Photographer's Guide to Los Santos is an ongoing project that builds on top of a research on artistic practices within spaces of computer games, with a particular focus on in-game photography, machinima and digital visual arts. It follows some themes and ideas previously explored in the exhibition [_How to Win at Photography_](https://www.howtowinat.photography/), while focusing more specifically on the relationship between computer games and photographic activities inside the world of Grand Theft Auto V.

The idea of a guide refers to in-game photography as a form of 'virtual tourism' ([Book, 2003](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=538182)), which was also the premise of an actual tourist guide published by Rough Guides in their 2019 [_Rough Guide to XBOX_](https://www.roughguides.com/articles/introduction-to-the-rough-guide-to-xbox/). Yet this guide project also understands the game world as a site for image production and artistic creation, turning the game into a destination for a 'game art tourist'. The Photographer's Guide to Los Santos presents the game environment of Grand Theft Auto V both as a space to explore and in which to create images, as well as a place to navigate and learn about some of the most important artworks that it has enabled to create. 

The project also brings together several experiences from teaching in-game photography as an artistic practice in different educational settings and institutions, compiling materials and tools for students and artists interested in engaging with the field. The tourist guide of the game world doubles as a photography manual for the in-game photography age, featuring tutorials and excercises ranging from game screenshotting to computer programming for creative modding. Through the practical excercises, the project invites to rethink the game object as a space for creative, subversive and critical endeavours, which can be played differently, documented, reclaimed or modified through an artistic approach. 

Finally, the project draws inspiration from the works of artists who have explored the 'metaplay' of photographing game words instead of following the game rules and attempt to reach the goal of winning. The Photographer's Guide to Los Santos is indebted to all the artists it features, but was particularly inspired by Gareth Damian Martin's live streamed workshop [_Photography Tour of No Man’s Sky_](https://www.twitch.tv/videos/591840067) (realized for [Now Play This Festival 2020](https://www.somersethouse.org.uk/whats-on/now-play-this-2020)), Total Refusal & Ismaël Joffroy Chandoutis's 2021 in-game lecture performance and guided tour [_Everyday Daylight_](https://vimeo.com/506064357) (realized for the [CCS Paris](https://ccsparis.com/en/events/total-refusal-digital-disarmament-movement-a-la-gaite-lyrique/)), and Alan Butler's epic 2020 live endurance performance [_Witness to a Changing West_](https://www.youtube.com/watch?v=R4Q2G6tOQ_Q) (realized for [Screen Walks](https://screenwalks.com/)) and his 'Content Replication Assignments'. 


## Why Los Santos?
Just like Los Angeles – the city it is modelled upon – is the global centre of film and commercial media production, Los Santos is the epicentre of in-game photography and machinima creation.
...

## Grand Theft Auto V Tourism
This guide allows players to explore the game environment following some of the most interesting artworks that have been created with(in) it. The guide is divided in thematic chapters that follow different artistic practices, taking place in different locations of the game environment, followed by different tutorials and exercises connected with the works and the space analyzed.
Each selected work is presented by a curatorial statement, introducing the work and its artistic relevance. The work is accompanied by information on the in-game location from which it was produced, inviting the readers to reach the destination in Grand Theft Auto V through maps and indications.


## Grand Theft Auto V Art Education
Each thematic chapter features a tutorial section that introduces different techniques and strategies to capture images within Grand Theft Auto V. The chapters are thought to be experienced in order, as the tutorials at times rely on knowledge that is built on top of previous lessons. Each tutorial is accompanied by content replication assignments, in which the readers is invited to use the skills learnd from each chapter to recreate a work presented in that section.
