# Nature Documentary

## Deercam by Brent Watanabe

artwork text

### Getting There


## Virtual Flora

artwork text

### Getting There

## Readings

## Tutorial

### Modding Introduction 

#### Preparation and Setup

+ Install Windows 11

+ Download and install [Steam](https://store.steampowered.com/about/) (with a copy of GTA V or buy the game if you do not have it. GTA V is 100+ GB so it will take a few hours depending on your internet connections)

+ Download [Script Hook V](https://store.steampowered.com/about/), go to the bin folder and copy ```dinput8.dll``` and ```ScriptHookV.dll``` files into your GTA V directory ```C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V```

+ Download [Script Hook V dot net](https://store.steampowered.com/about/), copy the ```ScriptHookVDotNet.asi``` file, ```ScriptHookVDotNet2.dll``` and ```ScriptHookVDotNet3.dll``` files into your GTA V directory ```C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V```

+ Create a new folder in GTA V directory and call it “scripts”.

+ Download and install [Visual Studio Community](https://store.steampowered.com/about/) (free version of VS). Open Visual Studio and check the .NET desktop development package and install it

+ Run GTA V and test if Script Hook V is working by pressing ```F4```. This should toggle the console view.


#### Creating a Mod File

+ Open Visual Studio

+ Select File > New > Project

+ Select Visual C# and Class Library (.NET Framework)

+ Give a custom file name (e.g. moddingTutorial)

+ Rename public class Class1 as “moddingTutorial” in the right panel Solution Explorer

+ In the same panel go to References and click add References… > Browse > browse to Downloads 

+ Select ScriptHookedVDotNet > ```ScriptHookVDotNet2.dll``` and ```ScriptHookVDotNet3.dll``` and add them

+ Also add ```System.Windows.forms```

+ Also add ```System.Drawing```

+ In your code file add the following lines on top:
```cs
using GTA;
using GTA.Math;
using System.Windows.Forms;
using System.Drawing;
using GTA.Native;
```

+ Modify class moddingTutorial to the following:
```cs
namespace moddingTutorial
{
  public class moddingTutorial : Script
  {
	  public moddingTutorial()
	  {
		  this.Tick += onTick;
      this.KeyUp += onKeyUp;
      this.KeyDown += onKeyDown;
	  }
	
	  private void onTick(object sender, EventArgs e)
	  {
	  }
	
	  private void onKeyUp(object sender, KeyEventArgs e)
	  {
	  }
 
	  private void onKeyDown(object sender, KeyEventArgs e)
	  {
	  	if (e.KeyCode == Keys.H)
	  	{
			  Game.Player.ChangeModel(PedHash.Cat); 
		  }
	  } 
  }
}
```

+ Save file

+ Go to Documents > Visual Studio > Project > moddingTutorial > moddingTutorial > ```moddingTutorial.cs```

+ Copy the .cs file in the GTA V directory inside the scripts folder

+ Open GTA V, run the game in Story Mode (mods are only allowed in single player mode, not in GTA Online) and press ‘H’ to see if the game turns your avatar into a cat

+ Note: every time you make changes to your .cs file in the scripts folder you can hit ```F4``` to open the console, type ```Reload()``` in the console for the program to reload the script and test again the changes.

#### onTick, onKeyUp and onKeyDown
The main events of Script Hook V Dot Net are onTick, onKeyUp and onKeyDown. Script Hook V Dot Net will invoke your functions whenever an event is called.

The code within the onTick brackets is executed every interval milliseconds (which is by default 0), meaning that the event will be executed at every frame, for as long as the game is running.

```cs
 private void onTick(object sender, EventArgs e)
	  {
      //code here will be executed every frame (or per usef defined interval)
	  }
```

If your function is written inside onKeyDown (withiin the curly brackets following onKeyUp(object sender, KeyEventArgs e){}), your code will be executed every time a key is pressed. If your function is written inside onKeyUp, your code will be executed every time a key is released.

```cs
private void onKeyUp(object sender, KeyEventArgs e)
	  {
      //code here will be executed whenever a key is released
	  }
private void onKeyDown(object sender, KeyEventArgs e)
	  {
      //code here will be executed whenever a key is pressed
	  } 
```

We can specify which code is executed based on what keys are pressed/released

```cs
private void onKeyDown(object sender, KeyEventArgs e)
	  {
	  	if (e.KeyCode == Keys.H)
	  	{
			   //code here will be executed whenever the key 'H' is pressed 
		  }
	  } 
```



#### Change Player Model

The player character is controlled as Game.Player. Game.Player can perform different functions, including changing the avatar model, and performing tasks.

Change the 3D model of your character by using the _ChangeModel_ function.
The _ChangeModel_ function needs a model ID, in order to load the model file of our game character.
You can browse through this list of models to find the one you want to try:  https://wiki.gtanet.work/index.php/Peds  

These models are all PedHashes, basically ID numbers within the PedHash group. Copy the name of the model below the image and add it to PedHash.
For example if you choose the model Cat, you’ll need to write _PedHash.Cat_.

To change the model of your player character into a cat you can write the following function:
```cs
Game.Player.ChangeModel(PedHash.Cat);
```
add it in your .cs file in the onKeyDown event, triggered by the pressing of the 'h' key:

<details>
  <summary>Example code</summary>

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
 
using GTA;
using GTA.Math;
using System.Windows.Forms;
using System.Drawing;
using GTA.Native;
 
 
namespace moddingTutorial
{
    public class moddingTutorial : Script
    {
		public moddingTutorial()
		{
			this.Tick += onTick;
			this.KeyUp += onKeyUp;
			this.KeyDown += onKeyDown;
		}
 
		private void onTick(object sender, EventArgs e) //this function gets executed continuously 
		{
		}
 
		private void onKeyUp(object sender, KeyEventArgs e)//everything inside here is executed only when we release a key
		{
		}
 
		private void onKeyDown(object sender, KeyEventArgs e) //everything inside here is executed only when we press a key
		{
			//when pressing 'H'
			if(e.KeyCode == Keys.H)
			{
				//change player char into a different model
				Game.Player.ChangeModel(PedHash.Cat); 
			}
		}
	}
}

```
</details>


#### Tasks

## Content Replication Assignment

### Deercam reenactment

Write a mod script to change your game character into a deer by pressing a key, and make it autonomously wander around Los Santos by pressing another key.


